version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    networks:
      - app-network
  backend:
    build: ./Backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb+srv://saurabh:Saurabh22%40Jeena@interview-ai-cluster.xsi92cy.mongodb.net/interview-master
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
