const { PDFDocument, rgb, degrees } = require('pdf-lib');

async function generateReportPDF(report) {
  const pdfDoc = await PDFDocument.create();
  
  const helvetica = await pdfDoc.embedFont('Helvetica');
  const helveticaBold = await pdfDoc.embedFont('Helvetica-Bold');
  
  let page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();
  
  let yPosition = height - 50;
  const margin = 40;
  const maxWidth = width - 2 * margin;
  const lineHeight = 14;
  const smallLineHeight = 12;

  const colors = {
    primary: rgb(0.2, 0.4, 0.8),
    dark: rgb(0.1, 0.1, 0.1),
    light: rgb(0.95, 0.95, 0.95),
    success: rgb(0.2, 0.7, 0.2),
    warning: rgb(0.9, 0.6, 0.1),
    danger: rgb(0.9, 0.2, 0.2)
  };

  const drawText = (text, fontSize = 12, fontColor = colors.dark, bold = false) => {
    if (yPosition < 50) {
      page = pdfDoc.addPage([612, 792]);
      yPosition = height - 50;
    }
    page.drawText(text, {
      x: margin,
      y: yPosition,
      size: fontSize,
      color: fontColor,
      font: bold ? helveticaBold : helvetica
    });
    yPosition -= lineHeight;
  };

  const drawSection = (title, items) => {
    if (yPosition < 100) {
      page = pdfDoc.addPage([612, 792]);
      yPosition = height - 50;
    }

    yPosition -= 10;
    page.drawText(title, {
      x: margin,
      y: yPosition,
      size: 14,
      color: colors.primary,
      font: helveticaBold
    });
    yPosition -= lineHeight + 5;

    page.drawLine({
      start: { x: margin, y: yPosition },
      end: { x: width - margin, y: yPosition },
      thickness: 1,
      color: colors.primary
    });
    yPosition -= lineHeight;

    if (Array.isArray(items)) {
      items.forEach(item => {
        if (yPosition < 50) {
          page = pdfDoc.addPage([612, 792]);
          yPosition = height - 50;
        }
        page.drawText(`• ${item}`, {
          x: margin + 20,
          y: yPosition,
          size: 10,
          color: colors.dark,
          font: helvetica
        });
        yPosition -= smallLineHeight;
      });
    }

    yPosition -= 5;
  };

  const drawHeaderBox = () => {
    page.drawRectangle({
      x: margin,
      y: yPosition - 40,
      width: maxWidth,
      height: 50,
      color: colors.light,
      borderColor: colors.primary,
      borderWidth: 2
    });

    page.drawText('Interview Preparation Report', {
      x: margin + 10,
      y: yPosition - 15,
      size: 16,
      color: colors.primary,
      font: helveticaBold
    });

    page.drawText(new Date().toLocaleDateString(), {
      x: margin + 10,
      y: yPosition - 35,
      size: 10,
      color: colors.dark,
      font: helvetica
    });

    yPosition -= 70;
  };

  drawHeaderBox();

  page.drawText(`Position: ${report.title || 'N/A'}`, {
    x: margin,
    y: yPosition,
    size: 12,
    color: colors.dark,
    font: helveticaBold
  });
  yPosition -= lineHeight + 5;

  const scoreColor = report.matchScore >= 80 ? colors.success : 
                     report.matchScore >= 60 ? colors.warning : colors.danger;
  
  page.drawText(`Match Score: ${report.matchScore || 0}%`, {
    x: margin,
    y: yPosition,
    size: 12,
    color: scoreColor,
    font: helveticaBold
  });
  yPosition -= lineHeight + 15;

  if (report.technicalQuestions && report.technicalQuestions.length > 0) {
    const technicalItems = report.technicalQuestions
      .slice(0, 5)
      .map(q => `Q: ${q.question || 'N/A'}`);
    drawSection('Technical Questions', technicalItems);
  }

  if (report.behavioralQuestions && report.behavioralQuestions.length > 0) {
    const behavioralItems = report.behavioralQuestions
      .slice(0, 5)
      .map(q => `Q: ${q.question || 'N/A'}`);
    drawSection('Behavioral Questions', behavioralItems);
  }

  if (report.skillGaps && report.skillGaps.length > 0) {
    const skillItems = report.skillGaps
      .slice(0, 10)
      .map(s => `${s.skill || 'N/A'} (${s.severity || 'Medium'})`);
    drawSection('Skill Gaps', skillItems);
  }

  if (report.preparationPlan && report.preparationPlan.length > 0) {
    const planItems = report.preparationPlan
      .slice(0, 5)
      .map(p => `Day ${p.day}: ${p.focus || 'N/A'}`);
    drawSection('Preparation Plan', planItems);
  }

  yPosition -= 20;
  page.drawText('Generated by Resume Analyzer', {
    x: margin,
    y: yPosition,
    size: 9,
    color: rgb(0.5, 0.5, 0.5),
    font: helvetica
  });

  return await pdfDoc.save();
}

module.exports = {
  generateReportPDF
};
